### PR TITLE
Support additional contracts

### PR DESCRIPTION
**Pull request by jjttjj**
I've been experimenting with blindly importing a large number of IB's contracts and have discovered a few small bugs. There might be more to come :)

IB uses IST to abbreviate "India Standard Time" in their timezone ids. This is not an official timezone abbreviation that's recognized by Jodatime. 
https://stackoverflow.com/questions/11264697/java-timezone-strange-behavior-with-ist
https://en.wikipedia.org/wiki/Time_in_India

IB has an IOPT contract type, aka a Dutch Warrant. They have a "NOEXP" expiry value which was breaking with the current expiry translation function.
More info on them here:
https://money.stackexchange.com/questions/7016/interactive-brokers-iopts-and-list-of-structured-products

### CODE REVIEW

**Comment by jjttjj** [comment]
Here's a contract query using "IST" time zone
`{:contract-id 255873889}`

And here's a dutch warrant:
`{:contract-id 303280929}`

Both these will throw an exception before these changes are applied but should work afterwards

**Comment by jsab** [comment]
Sorry, forgot to cherrypick this over the weekend, will do it this weekend

**Comment by jjttjj** [comment]
Thanks! No rush, just wanted to get pushing these things here out of the way since they're pretty much just minor omissions. 

I also just added one more thing. This one is slightly trickier and I'm not positive this is the ideal way to handle it. The security ID list should be included IB's contract data if you pay for their CUSIP data service (last item on here: https://www.interactivebrokers.com/en/index.php?f=14193). Ib sends it as a list of TagValues (https://interactivebrokers.github.io/tws-api/classIBApi_1_1TagValue.html#gsc.tab=0) But I just convert this list to a map of id type to id string. I've tested a large amount of IB's contract ID's and I believe all security types excluding bonds and it seems like currently the security-id-list always just has either a single ISIN value or nothing at all. 

So with this change a contract-details request will add the following to the resulting map:
```
{...
:security-id-list {:isin "US0231351067"}
...}

It's a little weird calling the key in the contract `:security-id-list` since it will be a map (or nil), not a list. But I figured I'd stick to the IB terminology for now.

**Comment by jsab** [comment]
I have cherry picked your commits into master and added a commit for release 0.1.11.

**Pull request closed without merging**
